apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset-agentic-de
  labels:
    app: agentic-de
    key: value
spec:
  replicas: <Replicas>
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
        - name: myapp
          image: <Image>
