apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset-agentic-de
  labels:
    app: agentic-de
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx
      type: front-end
  template:
    metadata:
      labels:
        app: my-nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:latest
